name: link graph content planner topic 
on:
  workflow_dispatch:
    inputs:
#       username:
#         description: username
#         type: enviroment
#         required: true
#       password:
#         description: password
#         type: enviroment
#         required: true
      keyword:
        description: keyword
        type: enviroment
        required: true
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps        
      - name: Install dependencies
        run: |
          sudo apt-get update      
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run demo
        run: |
          env HOME=/root python test.py
        env:
          keyword: '${{ github.event.inputs.keyword }}'
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: '${{ github.run_id }}'
          prerelease: false
          title: '${{ github.run_id }}'
          files: |
            output/*             
